name: PDF処理アクション（完全自動）

on:
  workflow_dispatch:

  schedule:
    - cron: '10 20 * * *'  # JST 05:10
    - cron: '10 3 * * *'   # JST 12:10
    - cron: '0 7 * * *'    # JST 16:00
    - cron: '10 12 * * *'  # JST 21:10
    - cron: '50 13 * * *'  # JST 22:50

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install pymupdf gspread google-api-python-client

      - run: python main.py
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

